# Site settings
title: Lorenzo Pattori
email: a2cc6b4dff9f6a77f82b59a485172643
url: https://lpattori.github.io
description: "Passionate about innovation and new business generation. Building highly motivated teams to develop industry break through solutions."
description2: "Software Engineer & MBA. Developing Deep Learning Models to create new business opportunities in the medical an the consumer market. Enjoy running, ski and tennis."
keywords: "Software Engineer, Artificial Intelligence, Deep Learning"
skills: "MBA & Software Engineer <br> Artificial Intelligence - Deep Learning Specialist"
meta_author: Pattori lorenzo
person: Lorenzo Pattori

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - formsubmit: to be added   https://formsubmit.co/
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: formsubmit

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Lorenzo Pattori
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/pattori
  - title: github
    url: http://github.com/lpattori
  - title: twitter
    url: http://twitter.com/lpattori

# Postal address (add as many lines as necessary)
address:
  - line: Buenos Aires
  - line: Argentina

# Credits content
credits: 'Photos by <b><i>Sofía</b></i><br>Designed by <b><i>Fer</b></i>'

# Build settings
markdown: kramdown
permalink: pretty
